name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject token into JS
        run: |
          sed -i "s|const GITHUB_TOKEN = ''|const GITHUB_TOKEN = '${{ secrets.GITHUB_TOKEN }}'|" settings-panel.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
